"""Public result and evidence contracts for independently organized research."""

from ..backtesting.benchmark_contracts import LimitBuyHold, NextOpenBuyHold
from ..backtesting.service import BacktestEvaluation

from .delivery import (
    DeliveryStage,
    DeliveryStatus,
    ValidationStatus,
    DeliveryReference,
    DeliveryDefinition,
    ConfirmationStatus,
    ConfirmationRecord,
    MandateItemKind,
    NumericRequirement,
    PerformanceRequirement,
    BenchmarkRequirement,
    MandateItem,
    ResearchMandate,
    CatalogDefinitionKind,
    CatalogDefinitionRef,
    ExperimentDefinitionRef,
    ComponentTestStatus,
    ComponentTestResult,
    ComponentEntry,
    ComponentPanel,
    CandidateIdentityRef,
    EvaluationEvidenceRef,
    CandidateEntry,
    SearchSummary,
    CandidateSet,
    FactStatus,
    FactValue,
    ExplanationKind,
    Explanation,
    TargetMandateBinding,
    CandidateAssessmentDelivery,
    CandidateInspectionDelivery,
    DeliveryContent,
    DeliveryIssue,
    DeliveryValidationScope,
    DeliveryValidation,
    PublicationFile,
    DeliveryReceipt,
    DeliveryValidationError,
    DeliveryConflictError,
    ComponentDefinitionRef,
    StageContent,
)

from .context import (
    ResearchBatchRef,
    ExperimentRef,
    ResearchContext,
)

from .evidence import (
    EvidenceRef,
    MaterialEvidenceWrite,
    EvaluationEvidenceWrite,
    EvidenceWriteRequest,
)

from .evaluation import (
    METRIC_SEMANTICS_VERSION,
    BuyHoldReplay,
    EvaluationBenchmark,
    EvaluationCost,
    EvaluationRequest,
    EvaluationIdentity,
    EvaluationLineage,
    EvaluationResult,
    EvaluationRun,
    EvaluationWindow,
)

from .evaluation_access import (
    EvaluationResources,
    EvaluationStatus,
    EvaluationError,
    EvaluationOutcome,
)

from .assessment import build_assessment_evidence

__all__ = [
    "BacktestEvaluation",
    'DeliveryStage',
    'DeliveryStatus',
    'ValidationStatus',
    'DeliveryReference',
    'DeliveryDefinition',
    'ConfirmationStatus',
    'ConfirmationRecord',
    'MandateItemKind',
    'NumericRequirement',
    'PerformanceRequirement',
    'BenchmarkRequirement',
    'MandateItem',
    'ResearchMandate',
    'CatalogDefinitionKind',
    'CatalogDefinitionRef',
    'ExperimentDefinitionRef',
    'ComponentTestStatus',
    'ComponentTestResult',
    'ComponentEntry',
    'ComponentPanel',
    'CandidateIdentityRef',
    'EvaluationEvidenceRef',
    'CandidateEntry',
    'SearchSummary',
    'CandidateSet',
    'FactStatus',
    'FactValue',
    'ExplanationKind',
    'Explanation',
    'TargetMandateBinding',
    'CandidateAssessmentDelivery',
    'CandidateInspectionDelivery',
    'DeliveryContent',
    'DeliveryIssue',
    'DeliveryValidationScope',
    'DeliveryValidation',
    'PublicationFile',
    'DeliveryReceipt',
    'DeliveryValidationError',
    'DeliveryConflictError',
    'ComponentDefinitionRef',
    'StageContent',
    'ResearchBatchRef',
    'ExperimentRef',
    'ResearchContext',
    'EvidenceRef',
    'MaterialEvidenceWrite',
    'EvaluationEvidenceWrite',
    'EvidenceWriteRequest',
    'METRIC_SEMANTICS_VERSION',
    'BuyHoldReplay',
    'EvaluationBenchmark',
    'EvaluationCost',
    'EvaluationRequest',
    'EvaluationIdentity',
    'EvaluationLineage',
    'EvaluationResult',
    'EvaluationRun',
    'EvaluationWindow',
    'EvaluationResources',
    'EvaluationStatus',
    'EvaluationError',
    'EvaluationOutcome',
    'build_assessment_evidence',
    'LimitBuyHold',
    'NextOpenBuyHold',
]
