"""Strategy Runtime (SRT) public contracts."""

from .algorithm import StrategyImplementation
from .identity import CandidateContentIdentity, ImplementationDependency
from .alignment import AlignmentRule, AlignedInput, InputAlignment, align_input_history
from .calculation import (
    CalculationScope,
    CalendarWindow,
    InputRange,
    next_session_calculation_scope,
    next_session_calendar_window,
)
from .binding import RuntimeBinding, RuntimeBindingSpec
from .observation import (
    OBSERVATION_CONTRACT_VERSION,
    materialize_observation,
    unavailable_observation,
    ObservationUnavailable, ObservationDefinition, ObservationSeries, ObservationFact, ConstantGuide, EvidenceGuide,
    ObservationValueType, ObservationFormat, StrategyObservation, ObservedSeries, ObservedFact,
)
from .contracts import (
    DataPreparationResult,
    ExecutionCapabilities,
    ExecutionOutcome,
    ExecutionOutcomeStatus,
    ExecutionPlan,
    ExecutionState,
    OrderSide,
    OrderType,
    PlanLeg,
    PlannedOrder,
    PortfolioSnapshot,
    PriceReference,
    StrategyIdentity,
    SignalHistoryMode,
    TradableWindow,
    TradingPoint,
    WindowExecutor,
)
from .errors import (
    RuntimeCompatibilityError,
    RuntimeContractError,
    RuntimeExecutionError,
    StrategyRuntimeError,
)
from .deployment import StrategyDeployment, deployment_inventory, load_strategy_deployment
from .models import (
    CutoffRule,
    DecisionContract,
    ExecutionPolicy,
    HistoryPolicy,
    ImplementationRef,
    InputContract,
    InputRequirement,
    MonitoringPolicy,
    ParameterSet,
    RequiredCapabilities,
    RuntimeDefinition,
    StrategyDefinition,
    StrategyCandidate,
    StrategyRelease,
    canonical_sha256,
)
from .implementation_identity import implementation_sha256
from .runtime import StrategyInit, StrategyRuntime
from .strategy import StrategyInstance

__version__ = "0.1.0"

__all__ = [
    "RuntimeBinding", "RuntimeBindingSpec",
    "ObservationUnavailable", "ObservationDefinition", "ObservationSeries", "ObservationFact", "ConstantGuide", "EvidenceGuide",
    "ObservationValueType", "ObservationFormat", "StrategyObservation", "ObservedSeries", "ObservedFact",
    "CandidateContentIdentity",
    "ImplementationDependency",
    "ExecutionOutcomeStatus",
    "SignalHistoryMode",
    "AlignedInput",
    "AlignmentRule",
    "DataPreparationResult",
    "CalculationScope",
    "CalendarWindow",
    "CutoffRule",
    "ExecutionCapabilities",
    "DecisionContract",
    "ExecutionOutcome",
    "ExecutionPlan",
    "ExecutionPolicy",
    "ExecutionState",
    "HistoryPolicy",
    "ImplementationRef",
    "InputContract",
    "InputAlignment",
    "InputRequirement",
    "InputRange",
    "MonitoringPolicy",
    "OrderSide",
    "OrderType",
    "OBSERVATION_CONTRACT_VERSION",
    "PlanLeg",
    "PlannedOrder",
    "PortfolioSnapshot",
    "PriceReference",
    "ParameterSet",
    "RequiredCapabilities",
    "RuntimeCompatibilityError",
    "RuntimeContractError",
    "RuntimeDefinition",
    "StrategyDefinition",
    "RuntimeExecutionError",
    "StrategyCandidate",
    "StrategyDeployment",
    "StrategyIdentity",
    "StrategyInit",
    "StrategyImplementation",
    "StrategyInstance",
    "StrategyRelease",
    "StrategyRuntime",
    "StrategyRuntimeError",
    "TradableWindow",
    "TradingPoint",
    "WindowExecutor",
    "canonical_sha256",
    "align_input_history",
    "deployment_inventory",
    "load_strategy_deployment",
    "materialize_observation",
    "implementation_sha256",
    "next_session_calculation_scope",
    "next_session_calendar_window",
    "unavailable_observation",
]
