"""Authenticated runtime binding, generated by the platform from a candidate."""

from dataclasses import asdict, dataclass
from pathlib import PurePosixPath
import re

from .errors import RuntimeCompatibilityError


def _require(ok, message):
    if not ok:
        raise RuntimeCompatibilityError(message)


@dataclass(frozen=True, slots=True)
class RuntimeBindingSpec:
    source_files: tuple[str, ...]
    implementation_sha256: str
    install_files: tuple[str, ...]
    observation_sha256: str

    def __post_init__(self):
        for values in (self.source_files, self.install_files):
            _require(
                type(values) is tuple and bool(values) and all(type(x) is str for x in values),
                "binding requires nonempty path tuples",
            )
            _require(len({x.casefold() for x in values}) == len(values), "binding repeats paths")
            for name in values:
                p = PurePosixPath(name)
                _require(
                    bool(p.parts)
                    and not p.is_absolute()
                    and ".." not in p.parts
                    and str(p) == name
                    and ":" not in name
                    and "\\" not in name,
                    "unsafe binding path",
                )
        _require(
            set(self.source_files) <= set(self.install_files), "install files omit source closure"
        )
        for value in (self.implementation_sha256, self.observation_sha256):
            _require(
                type(value) is str and re.fullmatch("[0-9a-f]{64}", value), "invalid binding hash"
            )

    def to_dict(self):
        return {
            "schema_version": 2,
            **asdict(self),
            "source_files": list(self.source_files),
            "install_files": list(self.install_files),
        }

    @classmethod
    def from_dict(cls, value):
        _require(
            type(value) is dict
            and set(value)
            == {
                "schema_version",
                "source_files",
                "implementation_sha256",
                "install_files",
                "observation_sha256",
            },
            "runtime binding spec fields differ",
        )
        _require(
            type(value["schema_version"]) is int and value["schema_version"] == 2,
            "runtime binding schema must be 2",
        )
        _require(
            type(value["source_files"]) is list and type(value["install_files"]) is list,
            "binding paths must be lists",
        )
        return cls(
            tuple(value["source_files"]),
            value["implementation_sha256"],
            tuple(value["install_files"]),
            value["observation_sha256"],
        )


@dataclass(frozen=True, slots=True)
class RuntimeBinding:
    release_id: str
    release_hash: str
    spec: RuntimeBindingSpec

    def __post_init__(self):
        _require(
            type(self.release_id) is str and re.fullmatch(r"S\d{3,}-v\d+", self.release_id),
            "invalid binding release id",
        )
        _require(
            type(self.release_hash) is str and re.fullmatch("[0-9a-f]{64}", self.release_hash),
            "invalid binding release hash",
        )
        _require(isinstance(self.spec, RuntimeBindingSpec), "binding spec must be typed")

    def to_dict(self):
        return {
            **self.spec.to_dict(),
            "release_id": self.release_id,
            "release_hash": self.release_hash,
        }

    @classmethod
    def from_dict(cls, value):
        _require(
            type(value) is dict and "release_id" in value and "release_hash" in value,
            "runtime binding lacks release identity",
        )
        return cls(
            value["release_id"],
            value["release_hash"],
            RuntimeBindingSpec.from_dict(
                {k: v for k, v in value.items() if k not in ("release_id", "release_hash")}
            ),
        )
